// Generated by https://quicktype.io

import 'package:cloud_firestore/cloud_firestore.dart';

class Popular {
  String? backdropPath;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  Popular({
    this.backdropPath,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });

  factory Popular.fromMap(Map<String, dynamic> map) {
    return Popular(
        id: map['id'],
        backdropPath: map['backdrop_path'],
        originalLanguage: map['original_language'],
        originalTitle: map['original_title'],
        overview: map['overview'],
        popularity: map['popularity'],
        posterPath: map['poster_path'],
        releaseDate: map['release_date'],
        title: map['title'],
        voteAverage: (map['vote_average'] is int)
            ? (map['vote_average'] as int).toDouble()
            : map['vote_average'],
        voteCount: map['vote_count']);
  }

  factory Popular.fromQuerySnapshot(QueryDocumentSnapshot document) {
    Map<String, dynamic> data = document.data() as Map<String, dynamic>;
    return Popular(
        id: data['id'],
        backdropPath: data['backdrop_path'],
        originalLanguage: data['original_language'],
        originalTitle: data['original_title'],
        overview: data['overview'],
        popularity: data['popularity'],
        posterPath: data['poster_path'],
        releaseDate: data['release_date'],
        title: data['title'],
        voteAverage: (data['vote_average'] is int)
            ? (data['vote_average'] as int).toDouble()
            : data['vote_average'],
        voteCount: data['vote_count']);
  }
}
